config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cars
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :people

  # Defines the root path route ("/")
  root 'people#index'
end

app/models/person.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: people
#
#  id         :bigint           not null, primary key
#  email      :string(255)
#  name       :string(255)
#  phone      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_people_on_email  (email) UNIQUE
#
class Person < ApplicationRecord
  has_many :cars, inverse_of: :owner, foreign_key: :owner_id, dependent: :nullify
  has_many :ownerships, -> { order(purchased_at: :desc) }, inverse_of: :person, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true,
                    email: { mode: :strict, require_fqdn: true },
                    uniqueness: { case_sensitive: false }
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]
  before_action :ensure_frame_response, only: %i[new edit show]

  # GET /people or /people.json
  def index
    @pagy, @people = load_all_people
  end

  # GET /people/1 or /people/1.json
  def show; end

  # GET /people/new
  def new
    @person = people_collection.new
  end

  # GET /people/1/edit
  def edit; end

  # POST /people or /people.json
  def create
    @person = people_collection.new(person_params)

    respond_to do |format|
      if @person.save
        render_saved_person(format, :created)
      else
        render_error(format, :new)
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        render_saved_person(format)
      else
        render_error(format, :edit)
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.turbo_stream { turbo_stream_replace_table }
      format.html { redirect_to people_url, notice: t('people.successfully_destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def load_all_people
    load_collection_paginated(people_collection.includes(:cars).all)
  end

  def render_error(format, action)
    format.html { render action, status: :unprocessable_entity }
    format.json { render json: @person.errors, status: :unprocessable_entity }
  end

  def render_saved_person(format, status = :ok)
    format.turbo_stream { turbo_stream_replace_table }
    format.html { redirect_to person_url(@person), notice: t('people.successfully_saved') }
    format.json { render :show, status:, location: @person }
  end

  def turbo_stream_replace_table
    pagy, people = load_all_people
    render turbo_stream: turbo_stream.replace('people-table', partial: 'people/people_table',
                                                              locals: { people:, pagy: })
  end

  def set_person
    @person = people_collection.includes(:ownerships, :cars).find(params[:id])
  end

  def person_params
    params.require(:person).permit(:name, :email, :phone)
  end

  def ensure_frame_response
    redirect_to root_path unless turbo_frame_request?
  end
end

app/helpers/people_helper.rb
# frozen_string_literal: true

module PeopleHelper
  def owner_info_link(person)
    turbo_frame_button(person, 'view-owner-button') do
      person.name
    end
  end
end

app/views/people/_form.html.slim
= form_with(model: @person) do |form|

  .row
    = form_group_for form, :name, label: bootstrap_icon("person", width: 15, height: 15)

    = form_group_for form, :email, label: bootstrap_icon("at", width: 15, height: 15)

    = form_group_for form, :phone, label: bootstrap_icon("telephone", width: 15, height: 15)

  .d-flex.justify-content-center.align-content-center.pt-3
    = form.submit class:"btn btn-primary", data: { disable_with: t('actions.saving') }

app/views/people/_people_table.html.slim
- if people&.any?
  #people-table.table-responsive
    table.table.table-striped.table-sm
      thead
        tr
          th #
          th = t('people.table.headers.name')
          th = t('people.table.headers.email')
          th = t('people.table.headers.phone')
          th = t('people.table.headers.car')
          th
      tbody#people-table-body
        = render partial: "person_row", collection: people, as: :person
    == pagy_bootstrap_nav(pagy)
- else
  #people-table.alert.alert-info.d-flex.justify-content-center.align-items-center
    = t('people.no_people')

app/views/people/_person.html.slim
div id="#{dom_id person}"
  .vstack.gap-3
    .hstack.gap-3
      = bootstrap_icon("at", width: 15, height: 15)
      = person.email
    .hstack.gap-3
      = bootstrap_icon("telephone", width: 15, height: 15)
      = number_to_phone(person.phone)

    - if person.ownerships.any?
      = render 'shared/ownership_history', parent: person

app/views/people/_person_row.html.slim
tr.person-row[id=dom_id(person)]
  td = person.id
  td = person.name
  td = person.email
  td = number_to_phone(person.phone)
  td
    - if person.cars.any?
      .vstack.gap-1
        - person.cars.each do |car|
          .car-item
            = car_info_link(car)
  td
    .d-flex.justify-content-evenly.flex-wrap.flex-md-nowrap.align-items-center
      = button_to person, class: 'view-button border border-0 bg-transparent', alt: t('table.actions.show'), method: :get, data: { turbo_frame: 'modal', bs_toggle: 'modal', bs_target: '#modalDialog' } do
        = bootstrap_icon "eye", width: 20, height: 20, fill: "grey"
      = button_to edit_person_path(person), class: 'edit-button border border-0 bg-transparent', alt: t('table.actions.edit'), method: :get, data: { turbo_frame: 'modal', bs_toggle: 'modal', bs_target: '#modalDialog' } do
        = bootstrap_icon "pencil-square", width: 20, height: 20, fill: "grey"
      = button_to person_path(person, page: params[:page]), alt: t('table.actions.destroy'), class: 'delete-button border border-0 bg-transparent', method: :delete, data: { 'turbo-method': :delete, turbo_confirm: t('table.actions.are_you_sure') } do
        = bootstrap_icon "trash-fill", width: 20, height: 20, fill: "grey"

app/views/people/edit.html.slim
= render TurboModalComponent.new(title: t('people.edit_person')) do
  == render "form", person: @person

app/views/people/index.html.slim
.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pt-3.pb-2.mb-3.border-bottom
  h1.h2 = t('people.title')
  .btn-toolbar.mb-2.mb-md-0
    .btn-group.me-2
      = button_to t('people.add_new'), new_person_path, method: :get, data: { turbo_frame: 'modal', bs_toggle: 'modal', bs_target: '#modalDialog' }, class: "add-new-button btn btn-sm btn-outline-secondary"

= render "people_table", people: @people, pagy: @pagy

app/views/people/new.html.slim
= render TurboModalComponent.new(title: t('people.new_person')) do
  == render "form", person: @person

app/views/people/show.html.slim
= render TurboModalComponent.new(title: @person.name) do
  == render @person