config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cars
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :people

  # Defines the root path route ("/")
  root 'people#index'
end

app/models/car.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: cars
#
#  id          :bigint           not null, primary key
#  color       :string(255)
#  is_for_sale :boolean          default(FALSE), not null
#  make        :string(255)
#  milage      :integer
#  model       :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  owner_id    :bigint
#
# Indexes
#
#  index_cars_on_owner_id  (owner_id)
#
# Foreign Keys
#
#  fk_rails_...  (owner_id => people.id)
#
class Car < ApplicationRecord
  belongs_to :owner, class_name: 'Person', optional: true
  has_many :ownerships, -> { order(purchased_at: :desc) }, inverse_of: :car, dependent: :destroy

  validates :model, :make, :color, :milage, presence: true
  validates :milage, numericality: { greater_than_or_equal_to: 0, less_than: 1_000_000 }
end

app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy]
  before_action :ensure_frame_response, only: %i[new edit show]

  # GET /cars or /cars.json
  def index
    @pagy, @cars = load_all_cars
  end

  # GET /cars/1 or /cars/1.json
  def show; end

  # GET /cars/new
  def new
    @car = cars_collection.new
  end

  # GET /cars/1/edit
  def edit; end

  # POST /cars or /cars.json
  def create
    @car = cars_collection.new(car_params)

    respond_to do |format|
      if @car.save
        render_saved_car(format, :created)
      else
        render_error(format, :new)
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        render_saved_car(format)
      else
        render_error(format, :edit)
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy

    respond_to do |format|
      format.turbo_stream { turbo_stream_replace_table }
      format.html { redirect_to cars_url, notice: t('cars.successfully_destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def load_all_cars
    load_collection_paginated(cars_collection.includes(:owner).order(sort_options).all)
  end

  def sort_options
    return { id: :asc } if params[:sort].blank?

    case params[:sort]
    when 'name'
      { make: sorting_direction, model: sorting_direction }
    when 'owner'
      { 'people.name' => sorting_direction }
    else
      { params[:sort] => sorting_direction }
    end
  end

  def render_error(format, action)
    format.html { render action, status: :unprocessable_entity }
    format.json { render json: @car.errors, status: :unprocessable_entity }
  end

  def render_saved_car(format, status = :ok)
    format.turbo_stream { turbo_stream_replace_table }
    format.html { redirect_to car_url(@car), notice: t('cars.successfully_saved') }
    format.json { render :show, status:, location: @car }
  end

  def turbo_stream_replace_table
    pagy, cars = load_all_cars
    render turbo_stream: turbo_stream.replace('cars-table', partial: 'cars/cars_table',
                                                            locals: { cars:, pagy: })
  end

  def set_car
    @car = cars_collection.includes(:ownerships, :owner).find(params[:id])
  end

  def car_params
    params.require(:car).permit(:model, :make, :color, :milage, :owner_id, :is_for_sale)
  end

  def ensure_frame_response
    redirect_to cars_path unless turbo_frame_request?
  end
end

app/helpers/cars_helper.rb
# frozen_string_literal: true

module CarsHelper
  def car_info_link(car)
    return '' unless car

    turbo_frame_button(car, 'view-car-button') do
      car_full_name(car)
    end
  end

  def car_full_name(car)
    return '' unless car

    "#{car.make} #{car.model}"
  end

  def car_for_sale(car)
    return yes_icon if car.is_for_sale

    no_icon
  end

  def owner_class(car)
    car.class.reflect_on_association(:owner).klass
  end

  def owners_for_select(car)
    options_for_select(
      [[t('select_one'), '']] +
        owner_class(car).order(:name).map { |person| [person.name, person.id] },
      car.owner_id
    )
  end

  def yes_icon
    bootstrap_icon('check2', width: 15, height: 15, class: 'text-success')
  end

  def no_icon
    bootstrap_icon('x', width: 15, height: 15, class: 'text-danger')
  end
end

app/views/cars/_car.html.slim
div id="#{dom_id car}"
  .vstack.gap-3
    .hstack.gap-3
      = bootstrap_icon("palette2", width: 15, height: 15)
      = car.color
      - if car.is_for_sale
        span.badge.bg-primary.text-end
          = t('for_sale')
    .hstack.gap-3
      = bootstrap_icon("speedometer2", width: 15, height: 15)
      = number_with_delimiter(car.milage, delimiter: ',')
      =< t('miles')
    - if car.owner.present?
      .hstack.gap-3
        = bootstrap_icon("person", width: 15, height: 15)
        = car.owner.name

    - if car.ownerships.any?
      = render 'shared/ownership_history', parent: car

app/views/cars/_car_row.html.slim
tr.car-row[id=dom_id(car)]
  td = car.id
  td = car_full_name(car)
  td = car.color
  td = number_with_delimiter(car.milage, delimiter: ',')
  td.ps-4 = car_for_sale(car)
  td = owner_info_link(car.owner) if car.owner.present?
  td.d-flex.justify-content-evenly.flex-wrap.flex-md-nowrap.align-items-center
    = button_to car, class: 'view-button border border-0 bg-transparent', alt: t('table.actions.show'), method: :get, data: { turbo_frame: 'modal', bs_toggle: 'modal', bs_target: '#modalDialog' } do
      = bootstrap_icon "eye", width: 20, height: 20, fill: "grey"
    = button_to edit_car_path(car), class: 'edit-button border border-0 bg-transparent', alt: t('table.actions.edit'), method: :get, data: { turbo_frame: 'modal', bs_toggle: 'modal', bs_target: '#modalDialog' } do
      = bootstrap_icon "pencil-square", width: 20, height: 20, fill: "grey"
    = button_to car_path(car, page: params[:page]), alt: t('table.actions.destroy'), class: 'delete-button border border-0 bg-transparent', method: :delete, data: { 'turbo-method': :delete, turbo_confirm: t('table.actions.are_you_sure') } do
      = bootstrap_icon "trash-fill", width: 20, height: 20, fill: "grey"

app/views/cars/_cars_table.html.slim
- if cars&.any?
  #cars-table.table-responsive
    table.table.table-striped.table-sm
      thead
        tr
          th #
          - cars_sorting_headers.each do |name|
            th = render 'shared/sorted_header', path: cars_path(params: sorting_pagination_params(name)), domain: :cars, field: name
          th
      tbody#cars-table-body
        = render partial: "car_row", collection: cars, as: :car
    == pagy_bootstrap_nav(pagy)
- else
  #cars-table.alert.alert-info.d-flex.justify-content-center.align-items-center
    = t('cars.no_cars')

app/views/cars/_form.html.slim
= form_with(model: @car) do |form|

  .row
    .field-is_for_sale-container.col-12.mb-2
      .form-check.form-switch.form-switch-md.d-flex.justify-content-start.align-items-center
        = form.check_box :is_for_sale, role: 'switch', class: 'form-check-input'
        = form.label :is_for_sale, class: 'form-check-label ms-3' do
          = t('cars.for_sale')

    = form_group_for form, :make, label: bootstrap_icon("car-front", width: 15, height: 15)
    = form_group_for form, :model, label: bootstrap_icon("car-front-fill", width: 15, height: 15)
    = form_group_for form, :color, label: bootstrap_icon("palette2", width: 15, height: 15)
    = form_group_for form, :milage, label: bootstrap_icon("speedometer2", width: 15, height: 15)
    = form_group_for form, :owner_id, type: :select, collection: owners_for_select(@car), label: bootstrap_icon("person", width: 15, height: 15)

  .d-flex.justify-content-center.align-content-center.pt-3
    = form.submit class:"btn btn-primary", data: { disable_with: t('actions.saving') }

app/views/cars/edit.html.slim
= render TurboModalComponent.new(title: t('cars.edit_car')) do
  == render "form", car: @car

app/views/cars/index.html.slim
.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pt-3.pb-2.mb-3.border-bottom
  h1.h2 = t('cars.title')
  .btn-toolbar.mb-2.mb-md-0
    .btn-group.me-2
      = button_to t('cars.add_new'), new_car_path, method: :get, data: { turbo_frame: 'modal', bs_toggle: 'modal', bs_target: '#modalDialog' }, class: "add-new-button btn btn-sm btn-outline-secondary"

= render "cars_table", cars: @cars, pagy: @pagy

app/views/cars/new.html.slim
= render TurboModalComponent.new(title: t('cars.new_car')) do
  == render "form", car: @car

app/views/cars/show.html.slim
= render TurboModalComponent.new(title: car_full_name(@car)) do
  == render @car